---
wireguard_interface: wg0
wireguard_address: 10.10.0.1/24
wireguard_listen_port: 51820
wireguard_peers: []
wireguard_manage_firewall: true
wireguard_allow_mesh_traffic: true
wireguard_private_key_path: "/etc/wireguard/{{ wireguard_interface }}.key"
