---
- name: Converge
  hosts: all
  become: true
  vars:
    wireguard_address: 10.10.0.1/24
    wireguard_manage_firewall: false
    wireguard_peers:
      - name: laptop
        public_key: nZ0Dk1Q5m6oM2h9mWMSaBpS1lE3fXpTK0cN4hGZL0S8=
        allowed_ips: 10.10.0.2/32
  roles:
    - role: "{{ lookup('ansible.builtin.env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
